name = "xui-sub-rules-worker"
main = "src/index.ts"
compatibility_date = "2026-05-21"

workers_dev = true

[[kv_namespaces]]
binding = "SUB_LINKS"
id = "32b8f0f2b21f49df8da179995ee38586"
preview_id = "32b8f0f2b21f49df8da179995ee38586"

[vars]
RULES_BASE_URL = "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release"


